#
# pass for whitelisted (public) routes
# block for blacklisted (disabled, banned) routes
#
rules:
  pass: 
    - api/v2/barong/identity/
    - api/v2/peatio/public/
  block:
    - api/v2/peatio/blocked/
    - api/v2/barong/blocked/
